spring:
  application:
    name: "TelegramBot"
telegram:
  token: ${BOT_TOKEN}
cloud:
  tokenTTL: ${TOKEN_TTL}
api:
  cloudServiceUrl: ${CB_URL}
server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
